### ISSUE TITLE
远端debug能否同时看到server的console，或者server的日志文件呢？

### ISSUE THREAD

**Issue by scxkd2016** [WangJi92/remote-debug-example#1]
远端debug能否同时看到server的console，或者server的日志文件呢？

**Comment by WangJi92** [comment]
可以看看你这篇文章 [源码、问题排查技巧-Java Debug and Arthas](https://wangji.blog.csdn.net/article/details/104591529)
![image](https://user-images.githubusercontent.com/20874972/79329698-d5d47700-7f4a-11ea-83ea-6709a9ed0588.png)
可以通过IDEA的断点打印，打印日志，打印堆栈，远程debug 只是和jvm 通信，不涉及服务器。[远程debug ](https://wangji.blog.csdn.net/article/details/104145967)
